-- Catalogo LG Perfumes. Ejecutar DESPUES de supabase.sql.
delete from public.perfumes;

insert into public.perfumes (nombre,marca,precio,stock,categoria,imagen_url,descripcion,notas_salida,notas_corazon,notas_fondo) values
('9AMFemmeEDP','AFNAN',2900,10,'Mujer','/perfumes/p02_01.png','','Limón, mandarina, cardamomo, pimienta rosa','Lavanda, flor de azahar, manzana verde, rosa','Almizcle, musgo, cedro, pachulí'),
('Men''s 9PM','AFNAN',2700,10,'Hombre','/perfumes/p02_02.png','','Manzana, canela, lavanda salvaje, bergamota','Flor de azahar, muguete','Vainilla, haba tonka, ámbar'),
('Men''sTurathi Blue','AFNAN',3500,10,'Hombre','/perfumes/p02_03.png','','Notas acuáticas, bergamota, limón','Lavanda, geranio, jazmín','Ámbar, almizcle, notas amaderadas'),
('Unicex 9AM','AFNAN',2900,10,'Unisex','/perfumes/p02_04.png','','Limón, mandarina, cardamomo, pimienta rosa','Lavanda, flor de azahar, manzana verde, rosa','Almizcle, musgo, cedro, pachulí'),
('Turathi Electric','AFNAN',4200,10,'Hombre','/perfumes/p02_05.png','','Pera, pomelo rosa, mandarina, bergamota','Flor de azahar, manzana, cedro','Almizcle, ámbar, vainilla'),
('Ladies 9pm Femme','AFNAN',2800,10,'Mujer','/perfumes/p02_06.png','','','',''),
('9PM DIVE','AFNAN',2700,10,'Hombre','/perfumes/p02_07.png','','Manzana, limón, bergamota','Jazmín, rosa','Vainilla, almizcle, ámbar'),
('9PM Elixir','AFNAN',3500,10,'Hombre','/perfumes/p02_08.png','','Cardamomo, nuez moscada, elemí','Pimienta, cuero, lavanda','Vainilla, pachulí, labdano, jara'),
('Rare Reef EDP','AFNAN',4200,10,'Unisex','/perfumes/p02_09.png','','Naranja, menta, cidra, pomelo, grosella negra, cilantro','Albaricoque, albahaca, hoja de violeta, rosa','Higo, ambreta, amberwood, dátiles'),
('9 PM Rebel','AFNAN',4200,10,'Hombre','/perfumes/p02_10.png','','Mandarina, piña, manzana verde','Notas florales','Notas amaderadas, vainilla, ámbar'),
('Supremacy In Oud','AFNAN',4200,10,'Hombre','/perfumes/p02_11.png','','','',''),
('Men''s Supremacy Silver','AFNAN',4200,10,'Hombre','/perfumes/p02_12.png','','Piña, grosella negra, bergamota, manzana','Abedul, pachulí, jazmín marroquí, rosa','Almizcle, musgo de roble, ámbar gris, vainilla'),
('Men''s Island Bliss Delights','ARMAF',4500,10,'Hombre','/perfumes/p03_01.png','','Bayas silvestres, notas verdes','Coco, flor de azahar, lactonas, nenúfar','Vainilla, haba tonka, almizcle'),
('Ladies Yum','ARMAF',4500,10,'Mujer','/perfumes/p03_02.png','','Bayas silvestres, cereza, naranja, bergamota','Rosa, flores blancas, vainilla','Notas empolvadas, almizcle, ámbar'),
('Man Connoisseur','ARMAF',3400,10,'Hombre','/perfumes/p03_03.png','','Manzana verde, pomelo, jengibre, aldehídos','Geranio, lavanda, salvia','Olíbano, haba tonka, pachulí, cedro'),
('WomenConnoisseur EDP','ARMAF',3400,10,'Mujer','/perfumes/p03_04.png','','','',''),
('Men''s Italia','ARMAF',2800,10,'Hombre','/perfumes/p03_05.png','','Cítricos, frutos rojos, naranja','Flor de azahar, azafrán, jazmín, rosa, caléndula','Ámbar, almizcle, iris'),
('Men''s Italiano Nero Uomo','ARMAF',2900,10,'Hombre','/perfumes/p03_06.png','','','',''),
('Ventana Pour Home','ARMAF',2700,10,'Hombre','/perfumes/p03_07.png','','Pomelo, limón, mandarina','Lavanda, geranio, vetiver, pachulí','Cedro, ámbar, maderas preciosas'),
('Ventana Marine','ARMAF',3800,10,'Hombre','/perfumes/p03_08.png','','Naranja siciliana, cidra, bergamota de Calabria, petitgrain, cardamomo','Jengibre, neroli, jazmín, romero, canela, muguete','Té chino, sándalo, palisandro, madera de guayaco'),
('Ladies Miss Attitude','ARMAF',3450,10,'Mujer','/perfumes/p03_09.png','','','',''),
('Men''s Tres Nuit','ARMAF',3650,10,'Hombre','/perfumes/p03_10.png','','Iris, limón, verbena','Lavanda, violeta, especias','Ámbar gris, sándalo'),
('Odyssey Marshmallow','ARMAF',3650,10,'Unisex','/perfumes/p03_11.png','','Coco, manzana, limón, peonía, muguete','Malvavisco, fresa, frambuesa, albaricoque, durazno, flor de azahar','Mascarpone, vainilla, praliné, almizcle, haba tonka, ámbar'),
('Ladies Odyssey Candee','ARMAF',2700,10,'Mujer','/perfumes/p03_12.png','Disponible en 2 presentaciones: RD$2,700 / RD$3,800','Fresa, frambuesa, geranio, durazno, bergamota','Caramelo, jazmín, maracuyá','Pachulí, almizcle, ámbar'),
('Men''s Odyssey Limoni','ARMAF',2700,10,'Hombre','/perfumes/p04_01.png','','Limón, naranja dulce, mandarina, bergamota','Flor de azahar, notas marinas, jengibre','Té, almizcle, ámbar'),
('Odyssey Mandarin Sky Elixir','ARMAF',3800,10,'Unisex','/perfumes/p04_02.png','','','',''),
('Men''s Odyssey Aoud','ARMAF',2700,10,'Hombre','/perfumes/p04_03.png','','Azafrán, nuez moscada, lavanda','Oud, notas amaderadas','Ambroxan, almizcle, pachulí'),
('Men''s Odyssey Tyrant','ARMAF',2700,10,'Hombre','/perfumes/p04_04.png','','Pomelo, cítricos','Pimienta, lavanda, geranio, elemí','Ambroxan, notas amaderadas, vetiver, cedro'),
('Men''s Odyssey Mega','ARMAF',2700,10,'Hombre','/perfumes/p04_05.png','','Naranja, limón, bergamota, jengibre, menta','Piña, salvia, enebro, geranio','Almizcle, cedro, haba tonka, vetiver'),
('Men''s Odyssey Artisto','ARMAF',3800,10,'Hombre','/perfumes/p04_06.png','','Bergamota, notas de nuez, salvia','Coco, frutas tropicales, canela','Vainilla, haba tonka, ámbar'),
('Men''s Odyssey Wild One','ARMAF',2700,10,'Hombre','/perfumes/p04_07.png','','Pimienta, bergamota, menta, limón','Pimienta rosa, lavanda, jengibre, vetiver','Cedro, pachulí, elemí, sándalo, almizcle'),
('Men''s Odyssey Homme Odyssey White Edition','ARMAF',2700,10,'Hombre','/perfumes/p04_08.png','Disponible en 2 presentaciones: RD$2,700 / RD$3,800','','',''),
('Men''s Odyssey Aqua','ARMAF',2700,10,'Hombre','/perfumes/p04_09.png','','Naranja, pomelo, artemisa','Menta, lavanda','Ambroxan, ciprés, pachulí'),
('Spectra','Men''s Odyssey',2700,10,'Hombre','/perfumes/p04_10.png','','','',''),
('Men''s Odyssey Eau De Montagne Mountain Edition','ARMAF',3650,10,'Hombre','/perfumes/p04_11.png','','Almendra, lactonas, especias','Flores blancas','Vainilla, sándalo, almizcle, cacao'),
('Men''s Odyssey Mandarin Sky','ARMAF',2700,10,'Hombre','/perfumes/p04_12.png','','Mandarina, naranja, azafrán, salvia','Caramelo, haba tonka, caléndula','Ambroxan, cedro, vetiver'),
('Odyssey Go Mango','ARMAF',2700,10,'Unisex','/perfumes/p05_01.png','','Limón, jengibre, flores blancas, pimienta rosa','Mango, madera seca, haba tonka','Ámbar, vainilla, madera de guayaco, almizcle, notas de nuez'),
('Odyssey Toffee Coffee','ARMAF',2700,10,'Unisex','/perfumes/p05_02.png','','Café, dulce de leche, miel, azafrán, bergamota','Toffee, lactonas, musgo de roble, flor blanca, rosa búlgara','Vainilla, caña de azúcar, ámbar, notas amaderadas, almizcle blanco'),
('Odyssey Dubai Chocolat','ARMAF',3650,10,'Unisex','/perfumes/p05_03.png','','Café, pistacho, avellana, praliné, knafeh','Chocolate, vainilla, cardamomo','Caramelo, amberwood, haba tonka'),
('Odyssey BA HA MAS','ARMAF',3800,10,'Unisex','/perfumes/p05_04.png','','','',''),
('Odyssey Spectra Blue','ARMAF',5300,10,'Unisex','/perfumes/p05_05.png','','Canela, manzana, bergamota','Canela, lavanda, flor de azahar, muguete','Tabaco, haba tonka, ámbar, pachulí, vainilla'),
('Odyssey Revolution','ARMAF',2700,10,'Unisex','/perfumes/p05_06.png','','Piña, grosella negra, naranja sanguina, salvia','Praliné, vainilla, ciruela, cardamomo','Pachulí, haba tonka'),
('Odyssey Black Forest','ARMAF',3650,10,'Unisex','/perfumes/p05_07.png','','Caramelo, cereza, canela, lactonas, flor blanca','Dátiles, miel, nuez moscada','Praliné, vainilla, haba tonka, notas amaderadas, almizcle'),
('Odyssey Mandarin Sky Vintage Edition','ARMAF',3800,10,'Unisex','/perfumes/p05_08.png','','','',''),
('Donna Di Terra','ARMAF',2700,10,'Mujer','/perfumes/p05_09.png','','Pimienta rosa, cítricos','Notas especiadas, rosa','Pachulí'),
('Tag Donna Colorata','ARMAF',2600,10,'Mujer','/perfumes/p05_10.png','','Bergamota, neroli, pimienta rosa','Flor de azahar, jazmín, rosa','Vainilla, almizcle, caramelo'),
('Tag Uomo Rosso Negro','ARMAF',2900,10,'Hombre','/perfumes/p05_11.png','','Pomelo, limón, bergamota, pimienta rosa','Jengibre, menta, lavanda, nuez moscada','Vetiver, sándalo, pachulí, cedro'),
('CheckMate King','ARMAF',3450,10,'Hombre','/perfumes/p05_12.png','','Mirabel, notas frutales','Castaña, acorde gourmand, especias','Sándalo, ámbar, notas empolvadas y balsámicas'),
('CheckMate Queen','ARMAF',2700,10,'Unisex','/perfumes/p06_01.png','','Nardo, notas verdes','Higo, especias','Notas empolvadas, sándalo'),
('Purple Amethyst Niche','ARMAF',3400,10,'Mujer','/perfumes/p06_02.png','','Lichi, rosa, limón','Rosa, magnolia, iris, flor de azahar','Almizcle, pachulí, ámbar'),
('Coral Pink by Niche','ARMAF',3500,10,'Mujer','/perfumes/p06_03.png','','Naranja, bergamota','Rosa, jazmín','Pachulí, vainilla, almizcle, vetiver'),
('Platinum by Niche','ARMAF',3450,10,'Hombre','/perfumes/p06_04.png','','Notas especiadas','Cedro, pachulí','Ámbar, mirra, ládano'),
('Oud by Niche','ARMAF',3550,10,'Unisex','/perfumes/p06_05.png','','Notas especiadas, alcaravea, salvia, bergamota','Pimienta negra, cedro, iris','Ámbar, vainilla, cuero, pachulí'),
('Unisex Desert Night','ARMAF',3400,10,'Unisex','/perfumes/p06_06.png','','Aceite de naranja, olíbano, pimienta rosa','Canela','Cuero, cedro, ámbar, sándalo, pachulí, haba tonka'),
('Ladies Desert Men''s Star','ARMAF',3400,10,'Hombre','/perfumes/p06_07.png','','Bergamota','Pimienta rosa, vetiver, madera de cachemira','Cedro, almizcle blanco, ámbar'),
('Men''s Desert Breeze','ARMAF',3400,10,'Hombre','/perfumes/p06_08.png','','Limón italiano, jazmín, muguete','Oud','Sándalo, almizcle'),
('Ladies Eter Desert','ARMAF',3400,10,'Mujer','/perfumes/p06_09.png','','','',''),
('Club de Nuit Urban Man Elixir','ARMAF',3800,10,'Hombre','/perfumes/p06_10.png','','Grosella negra, piña, limón, manzana, bergamota','Rosa, jazmín, notas amaderadas','Ambroxan, cuero, vainilla'),
('Club de Nuit Intense Club Man','ARMAF',2400,10,'Hombre','/perfumes/p06_11.png','','Limón, piña, bergamota, grosella negra, manzana','Rosa, jazmín, abedul','Ámbar gris, almizcle, vainilla, musgo de roble'),
('Club de Nuit Maleka','ARMAF',3900,10,'Unisex','/perfumes/p06_12.png','','Lichi, bergamota, pimienta rosa','Iris','Praliné, ambroxan, sándalo'),
('Club De Nuit Woman','ARMAF',2600,10,'Mujer','/perfumes/p07_01.png','','Naranja, bergamota, pomelo, durazno','Rosa, jazmín, geranio, lichi','Pachulí, almizcle, vainilla, vetiver'),
('Laddies Club de Nuit Imperiale','ARMAF',3950,10,'Unisex','/perfumes/p07_02.png','','Lichi, bergamota, nuez moscada','Rosa turca, vainilla, almizcle, peonía','Vainilla, incienso, cashmeran, cedro'),
('Club de Nuit Untold','ARMAF',3900,10,'Hombre','/perfumes/p07_03.png','','Azafrán, jazmín','Amberwood, ámbar gris','Resina de abeto, cedro'),
('Laddies Club de Nuit intense','ARMAF',2850,10,'Unisex','/perfumes/p07_04.png','','Piña, limón, grosella negra, manzana, bergamota','Jazmín, iris, abedul','Vainilla, ámbar gris, almizcle, musgo de roble'),
('Club De Nuit Milestone','ARMAF',3650,10,'Hombre','/perfumes/p07_05.png','','Notas marinas, frutos rojos, bergamota','Violeta, maderas blancas, sándalo','Almizcle, ambroxan, vetiver'),
('Club de Nuit Man Club','ARMAF',2700,10,'Hombre','/perfumes/p07_06.png','','Limón, manzana, bergamota','Rosa, jazmín, pachulí','Vainilla, almizcle, musgo de roble'),
('Club de Nuit Lionheart','ARMAF',3600,10,'Hombre','/perfumes/p07_07.png','','','',''),
('Club de Nuit Iconic','ARMAF',3600,10,'Hombre','/perfumes/p07_08.png','','','',''),
('ClubdeNuitSillage','ARMAF',3450,10,'Hombre','/perfumes/p07_09.png','','Bergamota, limón, lima, grosella negra, hoja de violeta, jengibre','Rosa, jazmín, iris','Ambroxan, almizcle, sándalo, cedro'),
('Club de Nuit Urban Man','ARMAF',4000,10,'Hombre','/perfumes/p07_10.png','','Lima, bergamota, cardamomo, tomillo','Enebro, geranio, jazmín, lavanda','Ambroxan, pachulí, cedro, ládano'),
('Club de Nuit Precieux','ARMAF',2600,10,'Unisex','/perfumes/p07_11.png','','Piña, limón, bergamota, caramelo, pimienta rosa, pera','Musgo de roble, madera blanca, jazmín, muguete, anís','Ambroxan, almizcle blanco, cedro, pachulí, ámbar, cuero, vainilla'),
('Ladies Club de Nuit Precieux IV','ARMAF',3900,10,'Mujer','/perfumes/p07_12.png','','','',''),
('The Lions Club Ruglr','ARMAF',3500,10,'Hombre','/perfumes/p08_01.png','','','',''),
('The Lions Club Monarque','ARMAF',3500,10,'Hombre','/perfumes/p08_02.png','','','',''),
('The Lions Club Feroce Amber','ARMAF AL',3500,10,'Hombre','/perfumes/p08_03.png','','','',''),
('Amber Oud Ruby Edition','AL HARAMAIN',3700,10,'Unisex','/perfumes/p08_04.png','','Azafrán, almendra amarga','Cedro, jazmín egipcio','Ámbar gris, notas amaderadas, almizcle'),
('Amber Oud Private Edition','AL HARAMAIN',4300,10,'Unisex','/perfumes/p08_05.png','','','',''),
('Amber Oud Gold Edition','AL HARAMAIN',4000,10,'Unisex','/perfumes/p08_06.png','','Notas verdes, bergamota','Notas dulces, melón, piña, cedro, ámbar','Notas amaderadas, almizcle, vainilla, mirra'),
('Amber Oud White Edition','AL HARAMAIN',3700,10,'Unisex','/perfumes/p08_07.png','','','',''),
('Edition Amber Oud Aqua Dubai','AL HARAMAIN',4200,10,'Unisex','/perfumes/p08_08.png','','','',''),
('Amber Oud Dubai Night','AL HARAMAIN',4200,10,'Unisex','/perfumes/p08_09.png','','','',''),
('Amber Oud Black Edition','AL HARAMAIN',3900,10,'Unisex','/perfumes/p08_10.png','','','',''),
('Amber Oud Blue','AL HARAMAIN',3700,10,'Unisex','/perfumes/p08_11.png','','Pomelo, limón, menta, pimienta rosa','Jengibre, vetiver, jazmín','Olíbano, sándalo, cedro, pachulí'),
('Amber Oud Carbon','AL HARAMAIN',3800,10,'Unisex','/perfumes/p08_12.png','','','',''),
('Amber Oud Rouge','AL HARAMAIN',3800,10,'Unisex','/perfumes/p09_01.png','','','',''),
('Cloud','ARIANA GRANDE',5000,10,'Mujer','/perfumes/p09_02.png','','Lavanda, pera, bergamota','Crema de coco, praliné, orquídea de vainilla','Maderas cremosas, almizcle'),
('Cloud 2.0 Intense','ARIANA GRANDE',5000,10,'Mujer','/perfumes/p09_03.png','','','',''),
('Cloud Pink','ARIANA GRANDE',5000,10,'Mujer','/perfumes/p09_04.png','','','',''),
('Thank U Next EDP','ARIANA GRANDE',3800,10,'Mujer','/perfumes/p09_05.png','','Frambuesa, pera','Coco, rosa rosada','Macarons, almizcle'),
('Sweet Like Cand','ARIANA GRANDE',5000,10,'Mujer','/perfumes/p09_06.png','','Mora, bergamota, pera','Crema batida, malvavisco, grosella negra, jazmín, madreselva, frangipani','Vainilla, madera de cachemira'),
('Ari','ARIANA GRANDE',5000,10,'Mujer','/perfumes/p09_07.png','','','',''),
('Wanted Eau de Parfum','AZZARO',4900,10,'Hombre','/perfumes/p09_08.png','','Jengibre, bergamota','Cardamomo, geranio','Vetiver, madera de guayaco, tabaco'),
('The Most Wanted Parfum','AZZARO',6900,10,'Hombre','/perfumes/p09_09.png','','Jengibre','Notas amaderadas','Vainilla bourbon'),
('The Most Wanted','AZZARO',5800,10,'Hombre','/perfumes/p09_10.png','','Cardamomo, jengibre','Toffee, caramelo','Amberwood'),
('Forever Wanted Elixir','AZZARO',7500,10,'Hombre','/perfumes/p09_11.png','','','',''),
('Wanted By Night','AZZARO',6500,10,'Hombre','/perfumes/p09_12.png','','Cardamomo, canela','Cuero, salvia','Vainilla, cedro, tabaco'),
('King','BHARARA',4100,10,'Hombre','/perfumes/p10_01.png','','Naranja, bergamota, limón','Notas frutales','Vainilla, almizcle blanco, ámbar'),
('Double Bleu','BHARARA',4700,10,'Hombre','/perfumes/p10_02.png','','Piña, limón, bergamota, romero','Jazmín, cilantro','Madera de deriva, almizcle'),
('Rose','BHARARA',4600,10,'Mujer','/perfumes/p10_03.png','','Rosa, azafrán','Oud, pachulí','Ámbar, almizcle'),
('Onix EDP','BHARARA',4700,10,'Hombre','/perfumes/p10_04.png','','Bergamota, flores, cilantro','Manzana, ambroxan, vainilla','Ámbar gris, haba tonka, notas amaderadas'),
('Chocolate','BHARARA',4850,10,'Unisex','/perfumes/p10_05.png','','Chocolate, café','Avellana, especias','Vainilla, ámbar'),
('Niche Femme','BHARARA',4900,10,'Mujer','/perfumes/p10_06.png','','','',''),
('Mast Perfume Rome','BHARARA',2700,10,'Unisex','/perfumes/p10_07.png','','','',''),
('Mast Perfume Rome Pour Femme','BHARARA',2900,10,'Mujer','/perfumes/p10_08.png','','','',''),
('Greenwich Village','BOND NO.9',16000,10,'Unisex','/perfumes/p10_09.png','','','',''),
('New York Nights','BOND NO.9',16500,10,'Unisex','/perfumes/p10_10.png','','Gardenia, clavel, jazmín','Pachulí, flores','Caramelo, vainilla, almizcle'),
('Chez Bond','BOND NO.9',13500,10,'Unisex','/perfumes/p10_11.png','','Bergamota, cilantro, enebro','Jazmín, hoja de violeta','Almizcle, sándalo, vetiver'),
('Gold Coast','BOND NO.9',13500,10,'Mujer','/perfumes/p10_12.png','','Lichi, manzana roja, albaricoque','Rosa francesa, sandía','Almizcle, vainilla, cedro'),
('Dubai Black Sapphire','BOND NO.9',18000,10,'Unisex','/perfumes/p11_01.png','','Azafrán, cera de abejas, miel, neroli','Bálsamo de gurjan, rosa turca, cedro, pimienta','Bálsamo de tolú, benjuí de Siam, sándalo, vetiver'),
('Ladies Omnia Amethyste','BVLGARI',7900,10,'Mujer','/perfumes/p11_02.png','','Toronjil, pimienta rosa','Rosa búlgara, iris','Madera de guayaco, almizcle'),
('Omnia Crystalline','BVLGARI',7400,10,'Mujer','/perfumes/p11_03.png','','Té blanco, loto, pera nashi','Bambú','Almizcle, notas amaderadas'),
('Omnia Coral','BVLGARI',5000,10,'Mujer','/perfumes/p11_04.png','','Bergamota, granada','Flor de loto, hibisco, jazmín','Almizcle, madera'),
('Man Glacial Essence','BVLGARI',6000,10,'Hombre','/perfumes/p11_05.png','','Bayas de enebro, jengibre, geranio','Sándalo, artemisa, raíz de iris','Clearwood, almizcle, cedro'),
('Man In Black Man','BVLGARI',6700,10,'Hombre','/perfumes/p11_06.png','','Bergamota, ron, especias','Cuero, tuberosa, iris, ámbar','Notas amaderadas, benjuí, almizcle, haba tonka'),
('Man Terrae Essence','BVLGARI',5000,10,'Hombre','/perfumes/p11_07.png','','Cidra, calamansí','Vetiver, iris','Notas terrosas, estoraque'),
('Ladies Goddess','BURBERRY',7900,10,'Mujer','/perfumes/p11_08.png','','Lavanda','Cacao, jengibre','Vainilla, ámbar'),
('Her / EDP','BURBERRY',6650,10,'Mujer','/perfumes/p11_09.png','','Fresa, frambuesa, mora, cereza, grosella negra','Violeta, jazmín','Almizcle, vainilla, cashmeran, pachulí, musgo'),
('London Womman','BURBERRY',4200,10,'Mujer','/perfumes/p11_10.png','','Madreselva, mandarina','Rosa, jazmín, flor de tiaré, peonía','Clementina, almizcle, sándalo, pachulí'),
('London Men','BURBERRY',4000,10,'Hombre','/perfumes/p11_11.png','','Lavanda, bergamota, hoja de tabaco, canela','Menta, cuero','Haba tonka, madera de guayaco, opopónaco'),
('Ladies My Black','BUBERRY',6200,10,'Mujer','/perfumes/p11_12.png','','Grosella negra, jazmín','Rosa','Ámbar, pachulí'),
('Men''s Hero Parfum','BURBERRY',8300,10,'Hombre','/perfumes/p12_01.png','','Amyris','Cedro','Aceite de cypriol (nagarmotha)'),
('Men''s Hero','BURBERRY',6100,10,'Hombre','/perfumes/p12_02.png','','Agujas de pino, olíbano','Benjuí, incienso','Cedro del Atlas, del Himalaya y de Virginia'),
('Men''s Hero Intense Parfum','BURBERRY',10800,10,'Hombre','/perfumes/p12_03.png','','Bergamota, agujas de pino','Incienso, benjuí','Cedro, ámbar'),
('Bad Boy Extreme EDP','CAROLINA HERRERA',6800,10,'Hombre','/perfumes/p12_04.png','','Ciruela, pimienta','Cacao, incienso','Haba tonka, ámbar'),
('Bad Boy Cobalt','CAROLINA HERRERA',5750,10,'Hombre','/perfumes/p12_05.png','','Bergamota, pimienta rosa, lavanda','Geranio, hoja de violeta','Amberwood, cedro, vetiver'),
('Bad Boy Cobalt Elixir 212','CAROLINA HERRERA',6800,10,'Hombre','/perfumes/p12_06.png','','Pimienta negra, salvia','Trufa, notas amaderadas','Vainilla, incienso'),
('212 Vip This Is a Private Party','CAROLINA HERRERA',5500,10,'Mujer','/perfumes/p12_07.png','','','',''),
('Ch / EDT','CAROLINA HERRERA',6150,10,'Unisex','/perfumes/p12_08.png','','','',''),
('212 Nyc For Men','CAROLINA HERRERA',5500,10,'Hombre','/perfumes/p12_09.png','','Bergamota, pomelo, especias verdes','Flor de lavanda, salvia, geranio','Sándalo, almizcle, incienso'),
('212 Vip Black','CAROLINA HERRERA',6100,10,'Hombre','/perfumes/p12_10.png','','Absenta, anís, hinojo','Lavanda','Vaina de vainilla negra, almizcle'),
('212 Vip Black Elixir','CAROLINA HERRERA',10800,10,'Hombre','/perfumes/p12_11.png','','Lavanda, salvia','Absenta, azafrán','Cuero, vainilla, vetiver'),
('212 Vip Rose','CAROLINA HERRERA',6300,10,'Mujer','/perfumes/p12_12.png','Disponible en 2 presentaciones: RD$6,300 / RD$6,850','Champán, flor de durazno','Rosa','Almizcle, notas amaderadas'),
('Obsession Men','CALVIN KLEIN',3250,10,'Hombre','/perfumes/p13_01.png','','Mandarina, lavanda, hoja de laurel, bergamota, especias','Nuez moscada, clavo, canela, pachulí, cilantro','Ámbar, almizcle, sándalo, vainilla, incienso'),
('CK One','CALVIN KLEIN',3500,10,'Unisex','/perfumes/p13_02.png','','Piña, papaya, bergamota, cardamomo, limón, mandarina, notas verdes','Nuez moscada, violeta, flor de azahar, jazmín, muguete, rosa','Almizcle, ámbar, notas amaderadas, musgo de roble'),
('Men''s Eternity','CALVIN KLEIN',3900,10,'Hombre','/perfumes/p13_03.png','','Lavanda, mandarina, bergamota, limón, salvia','Cilantro, muguete, geranio, jazmín','Sándalo, vetiver, ámbar, almizcle'),
('Sauvage/Christian Parfum','DIOR',9300,10,'Hombre','/perfumes/p13_04.png','','','',''),
('Sauvage/Christian EDT','DIOR',9300,10,'Hombre','/perfumes/p13_05.png','','Bergamota de Calabria, pimienta','Pimienta de Sichuan, lavanda, pimienta rosa, vetiver, pachulí, geranio, elemí','Ambroxan, cedro, labdano'),
('Christian/Sauvage Elixir','DIOR',9300,10,'Hombre','/perfumes/p13_06.png','','','',''),
('Christian Men''s Homme Intense','DIOR',9500,10,'Hombre','/perfumes/p13_07.png','','Lavanda','Iris, ambreta, pera','Vetiver, cedro, madera de cachemira'),
('Homme Christian Ladies Miss Dior','DIOR',9300,10,'Hombre','/perfumes/p13_08.png','','Rosa, mandarina siciliana','Rosa de Grasse, peonía, muguete','Almizcle, pachulí, notas amaderadas'),
('Nitro Blue','DUMONT',3600,10,'Hombre','/perfumes/p13_09.png','','','',''),
('Nitro Red','DUMONT',3600,10,'Hombre','/perfumes/p13_10.png','','','',''),
('Nitro White','DUMONT',3600,10,'Hombre','/perfumes/p13_11.png','','','',''),
('Nitro Green','DUMONT',3600,10,'Hombre','/perfumes/p13_12.png','','','',''),
('Light Blue Eau Intense','DOLCE&GABBANA',3600,10,'Mujer','/perfumes/p14_01.png','','Limón, manzana verde, pomelo','Jazmín sambac, agua marina','Almizcle, amberwood'),
('Ladies Devotion','DOLCE&GABBANA',6000,10,'Mujer','/perfumes/p14_02.png','','Limón confitado','Flor de azahar','Vainilla, panettone cremoso'),
('Light Blue','DOLCE&GABBANA',5050,10,'Mujer','/perfumes/p14_03.png','','Limón siciliano, manzana verde, campanilla','Bambú, jazmín, rosa blanca','Cedro, almizcle, ámbar'),
('Men''s The One','DOLCE&GABBANA',3600,10,'Hombre','/perfumes/p14_04.png','','Pomelo, cilantro, albahaca','Cardamomo, jengibre, flor de azahar','Ámbar, tabaco, cedro'),
('Ladies Devotion Intense','DOLCE&GABBANA',6700,10,'Mujer','/perfumes/p14_05.png','','Avellana','Flor de azahar','Vainilla'),
('Men''s K','DOLCE&GABBANA',6500,10,'Hombre','/perfumes/p14_06.png','','Naranja sanguina, limón siciliano','Higo, azafrán','Cuero, notas amaderadas'),
('Azzure Aoud','FRAGRANCE WORLD',3550,10,'Unisex','/perfumes/p14_07.png','','Maracuyá, notas frutales, rosa, azafrán','Oud, benjuí, pachulí','Cuero, madera de guayaco, ámbar, cedro, sándalo, vainilla, labdano'),
('Men''s French Avenue Liquid Brun','FRAGRANCE WORLD',3600,10,'Hombre','/perfumes/p14_08.png','','Canela, flor de azahar, cardamomo, bergamota','Vainilla bourbon, elemí','Notas amaderadas, ámbar'),
('French Avenue Cocoa Morado','FRAGRANCE WORLD',3550,10,'Unisex','/perfumes/p14_09.png','','Canela, azafrán, cardamomo','Dátiles, caramelo, oud, incienso','Vainilla, ámbar, notas amaderadas'),
('Ladies French Avenue Sweet Paradise','FRAGRANCE WORLD',3550,10,'Mujer','/perfumes/p14_10.png','','','',''),
('Ladies French Avenue Meringue','FRAGRANCE WORLD',2900,10,'Mujer','/perfumes/p14_11.png','','','',''),
('Ivory Musk','FRAGRANCE WORLD',3550,10,'Unisex','/perfumes/p14_12.png','','','',''),
('Acqua di Gio Profondo','GIORGO ARMANI',7900,10,'Hombre','/perfumes/p15_01.png','','Notas marinas, aquozone, bergamota, mandarina verde','Romero, lavanda, ciprés, lentisco','Notas minerales, almizcle, pachulí, ámbar'),
('Spectre Ghost','FRAGRANCE WORLD',3550,10,'Hombre','/perfumes/p15_02.png','','','',''),
('French Avenue Unisex Irida Extrait','FRAGRANCE WORLD',4500,10,'Unisex','/perfumes/p15_03.png','','','',''),
('Acqua di Gio Parfum','GIORGO ARMANI',8900,10,'Hombre','/perfumes/p15_04.png','','Bergamota, mandarina, notas marinas','Salvia, romero, geranio','Pachulí, incienso, amberwood, sal marina'),
('Absolutely Stronger With You','GIORGO ARMANI',7800,10,'Hombre','/perfumes/p15_05.png','','Jengibre, cardamomo','Toffee, notas verdes','Vainilla, ámbar, haba tonka'),
('Parfum Stronger With You','GIORGO ARMANI',8500,10,'Hombre','/perfumes/p15_06.png','','Pimienta rosa, mandarina','Lavanda, canela, salvia','Castaña, vainilla, cuero'),
('Because Its You','GIORGO ARMANI',5000,10,'Mujer','/perfumes/p15_07.png','','Frambuesa, pera','Jazmín, flor de naranja','Vainilla, pachulí, almizcle'),
('Intensely Stronger You With You','GIORGO ARMANI',7900,10,'Hombre','/perfumes/p15_08.png','','Lavanda, salvia, pimienta rosa','Toffee, canela','Vainilla, ámbar, haba tonka'),
('Ambassador','GISADA',6500,10,'Hombre','/perfumes/p15_09.png','','Mandarina verde, manzana, cardamomo, violeta','Mango, lavanda, pimienta negra, pachulí, peonía','Vainilla, ámbar, madera de teca, vetiver, musgo'),
('Ambassador Intense','GISADA',7300,10,'Hombre','/perfumes/p15_10.png','','Bergamota, cardamomo, manzana','Lavanda, pimienta, pachulí','Vainilla, ámbar, notas amaderadas, vetiver'),
('Ladies Ambassador','GISADA',5750,10,'Mujer','/perfumes/p15_11.png','','Bergamota, pera, grosella','Rosa, jazmín, flor de naranja','Vainilla, almizcle, sándalo, pachulí'),
('Iconic EDP','GUESS',3400,10,'Mujer','/perfumes/p15_12.png','','','',''),
('Seductive Red','GUESS',2700,10,'Mujer','/perfumes/p16_01.png','','','',''),
('Seductive Noir','GUESS',2700,10,'Mujer','/perfumes/p16_02.png','','','',''),
('Seductive Homme','GUESS',2700,10,'Hombre','/perfumes/p16_03.png','','Bergamota, romero, cardamomo, artemisa','Lavanda, salvia, notas acuáticas','Almizcle, cedro, ámbar'),
('Men''s Seductive Red','GUESS',2700,10,'Hombre','/perfumes/p16_04.png','','','',''),
('Ladies Bella Vita','GUESS',3500,10,'Mujer','/perfumes/p16_05.png','','Cereza ácida, grosella negra, limón italiano','Tuberosa, orquídea de vainilla, jazmín','Praliné, haba tonka, amberwood, almizcle'),
('Ladies EDP','GUESS',3200,10,'Mujer','/perfumes/p16_06.png','','','',''),
('Gentleman edp','GIVENCHY',7000,10,'Hombre','/perfumes/p16_07.png','','Pera, cardamomo','Iris, lavanda','Cuero, pachulí, vainilla, ámbar negro'),
('Gentleman EDT','GIVENCHY',4300,10,'Hombre','/perfumes/p16_08.png','','Pimienta, cardamomo','Iris, cuero','Pachulí, incienso, haba tonka'),
('Gentleman edt','GIVENCHY',5700,10,'Hombre','/perfumes/p16_09.png','','Pimienta, cardamomo','Iris, cuero','Pachulí, incienso, haba tonka'),
('Reserve Privee','GIVENCHY',6900,10,'Hombre','/perfumes/p16_10.png','','Bergamota','Iris, castaña','Ámbar, whisky, maderas'),
('Ange Ou Demon Le Secret','GIVENCHY',5200,10,'Mujer','/perfumes/p16_11.png','','Té blanco, mandarina','Jazmín, lirio de los valles','Vainilla, almizcle, pachulí'),
('Irresistible','GIVENCHY',5900,10,'Mujer','/perfumes/p16_12.png','','Pera, bergamota','Rosa, iris','Almizcle, madera de cachemira'),
('Pi','GIVENCHY',4800,10,'Hombre','/perfumes/p17_01.png','','Mandarina, albahaca, romero','Haba tonka, benjuí','Vainilla, ámbar, cedro, madera de guayaco'),
('Ladies L''Interdit','GIVENCHY',7200,10,'Mujer','/perfumes/p17_02.png','','','',''),
('Bottled Absolu Intense Parfum','HUGO BOSS',9200,10,'Hombre','/perfumes/p17_03.png','','Bergamota, cardamomo','Ámbar, especias','Cuero, olíbano, sándalo'),
('Intense Bottled Elixir Intense Parfum','HUGO BOSS',6900,10,'Hombre','/perfumes/p17_04.png','','Olíbano, cardamomo','Pachulí, vetiver','Labdano, cedro'),
('Boss Bottled','HUGO BOSS',4900,10,'Hombre','/perfumes/p17_05.png','','Manzana, ciruela, bergamota, limón','Geranio, canela, clavo, caoba','Sándalo, vainilla, cedro, vetiver, musgo de roble'),
('Boss Bottled Night','HUGO BOSS',4300,10,'Hombre','/perfumes/p17_06.png','','Lavanda, notas frescas','Cardamomo, violeta, cuero de abedul','Almizcle, sándalo'),
('Bottled Parfum','HUGO BOSS',5300,10,'Hombre','/perfumes/p17_07.png','','Bergamota, pimienta rosa','Iris, geranio','Notas amaderadas, ámbar, incienso, pachulí'),
('The Scent For Her','HUGO BOSS',4800,10,'Mujer','/perfumes/p17_08.png','','Osmanto','Flor de durazno, fresia','Cacao, miel'),
('Le Male Elixir Parfum','JEAN PAUL GAULTIER',6200,10,'Hombre','/perfumes/p17_09.png','Disponible en 2 presentaciones: RD$6,200 / RD$8,400','Menta, lavanda','Haba tonka','Vainilla, miel, benjuí'),
('Le Beau EDT Le','JEAN PAUL GAULTIER JEAN',7400,10,'Hombre','/perfumes/p17_10.png','','Bergamota','Coco','Ambroxan, haba tonka, notas amaderadas'),
('Le Beau Paradise Garden','JEAN PAUL GAULTIER',8300,10,'Hombre','/perfumes/p17_11.png','','','',''),
('Le Male Le Parfum','JEAN PAUL GAULTIER',7800,10,'Hombre','/perfumes/p17_12.png','','Cardamomo, lavanda','Canela','Vainilla, ámbar, benjuí'),
('Ladies Gaultier Divine Elixir Parfum','JEAN PAUL GAULTIER',10300,10,'Mujer','/perfumes/p18_01.png','','','',''),
('Scandal Absolu Parfum','JEAN PAUL GAULTIER JEAN',7500,10,'Unisex','/perfumes/p18_02.png','','','',''),
('Ladies Divine EDP','JEAN PAUL GAULTIER',7200,10,'Mujer','/perfumes/p18_03.png','','Brisa marina salada','Flores blancas, lirio','Merengue cremoso, vainilla'),
('Ladies Divine Le Parfum','JEAN PAUL GAULTIER JEAN',8950,10,'Mujer','/perfumes/p18_04.png','','','',''),
('Ladies La Belle','JEAN PAUL GAULTIER JEAN',7200,10,'Mujer','/perfumes/p18_05.png','','Pera, bergamota','Notas florales, cuero','Vainilla, vetiver, ámbar, almizcle'),
('Ladies La Belle Paradise Garden','JEAN PAUL GAULTIER',5700,10,'Mujer','/perfumes/p18_06.png','','','',''),
('Game Of Spades Diamond','JO MILANO',4900,10,'Unisex','/perfumes/p18_07.png','','Coñac, pimienta negra, naranja','Canela, haba tonka, roble, lavanda','Ámbar, vainilla, praliné, sándalo'),
('Game Of Spades Royale','JO MILANO',5300,10,'Unisex','/perfumes/p18_08.png','','Cacao, avellana','Jazmín sambac, cedro','Caramelo, ambroxan, musgo'),
('Game Of Spades Ruby','JO MILANO',5200,10,'Unisex','/perfumes/p18_09.png','','Bergamota, azafrán','Geranio, magnolia, rosa','Notas amaderadas, ámbar, civeta'),
('Game Of Spades Wildcard','JO MILANO',4900,10,'Unisex','/perfumes/p18_10.png','','Flores, bergamota, cilantro','Manzana, ambroxan, vainilla','Notas amaderadas, haba tonka, ámbar gris'),
('Game Of Spades King','JO MILANO',4900,10,'Hombre','/perfumes/p18_11.png','','Naranja, limón, bergamota','Frutas','Vainilla de Madagascar, ámbar, almizcle blanco'),
('Games Of Spades Win','JO MILANO',4900,10,'Mujer','/perfumes/p18_12.png','','Lichi, mandarina, cassis','Nenúfar, peonía, jazmín','Ambroxan, praliné, almizcle, musgo de roble, vainilla'),
('Game Of Spades Blind-Bid','JO MILANO',5300,10,'Unisex','/perfumes/p19_01.png','','Lichi, bergamota, pera','Rosa turca, oud, incienso','Notas amaderadas, vainilla, almizcle, ámbar, vetiver'),
('Game Of Spades Moon','JO MILANO',5300,10,'Unisex','/perfumes/p19_02.png','','Notas marinas, gardenia','Jazmín, clavel, café','Caramelo, sándalo, pachulí'),
('Game Of Spades Boston','JO MILANO',5300,10,'Unisex','/perfumes/p19_03.png','','Piña, bergamota, bayas de enebro','Brotes de grosella negra','Cedro, vetiver'),
('Game Of Spades Full-House','JO MILANO',5300,10,'Unisex','/perfumes/p19_04.png','','Cidra, bergamota de Calabria, naranja siciliana','Jengibre, neroli, canela de Ceilán','Té negro chino, ambroxan, madera de guayaco, olíbano'),
('Game Of Spades Queen','JO MILANO',4900,10,'Mujer','/perfumes/p19_05.png','','Mandarina, fresia','Jazmín sambac, rosa, lirio','Almizcle, sándalo, ámbar'),
('Game Of Spades Ace','JO MILANO',4900,10,'Unisex','/perfumes/p19_06.png','','Flor de azahar, ralladura de limón','Especias','Almizcle, ámbar, sándalo'),
('Game Of Spades Jackpot','JO MILANO',4900,10,'Unisex','/perfumes/p19_07.png','','Cítricos, bergamota','Notas frutales, notas dulces','Vainilla, ámbar, almizcle'),
('Game Of Spades Bid','JO MILANO',4900,10,'Unisex','/perfumes/p19_08.png','','Violeta, cardamomo','Iris, ambroxan','Sándalo, cedro, cuero'),
('Game of Spades Double Bonus','JO MILANO',5600,10,'Unisex','/perfumes/p19_09.png','','Bergamota, mandarina, naranja','Pimienta rosa, pimienta, cardamomo, nuez moscada, neroli','Vetiver'),
('Game Of Spades Bonus Parfum','JO MILANO',4900,10,'Unisex','/perfumes/p19_10.png','','Cilantro, grosella negra, menta, cidra, naranja, limón','Rosa de mayo, semillas de zanahoria, albahaca, albaricoque','Ambreta, higo, dátiles'),
('Game Of Spades High Roller','JO MILANO',5300,10,'Unisex','/perfumes/p19_11.png','','Grosella negra, pomelo, bergamota','Cardamomo, canela, jengibre, cidra','Pimienta rosa, pachulí'),
('Game Of Spades Yellow Sapphire','JO MILANO',5300,10,'Unisex','/perfumes/p19_12.png','','Rosa','Haba tonka, oud','Almizcle, vainilla'),
('Game Of Spades No Limit','JO MILANO',5200,10,'Unisex','/perfumes/p20_01.png','','Cítricos','Iris, amyris','Haba tonka, ámbar'),
('Game of Spades Emerald','JO MILANO',5200,10,'Unisex','/perfumes/p20_02.png','','Jengibre, pomelo, bergamota','Jengibre, neroli, flor de azahar','Almizcle, ambreta'),
('Game of Spades All-In','JO MILANO',6000,10,'Unisex','/perfumes/p20_03.png','','Naranja sanguina, bergamota, limón, lima, mandarina roja','Flor de tiaré','Notas empolvadas, almizcle, sándalo'),
('La Vie Est Belle EDP','LANCOME',6700,10,'Mujer','/perfumes/p20_04.png','','','',''),
('Asad Zanzibar','LATTAFA',2700,10,'Hombre','/perfumes/p20_05.png','','Lavanda, pimienta negra','Agua de coco, iris, sal','Vainilla, incienso'),
('Asad','LATTAFA',2700,10,'Hombre','/perfumes/p20_06.png','','Pimienta negra, tabaco, piña','Pachulí, café, iris','Vainilla, ámbar, maderas secas, benjuí, labdano'),
('Asad Bourbon','LATTAFA',2700,10,'Hombre','/perfumes/p20_07.png','','Lavanda, ciruela mirabel, pimienta rosa','Cacao, nuez moscada, davana','Vainilla bourbon, ámbar, vetiver'),
('Asad Elixir','LATTAFA',3600,10,'Hombre','/perfumes/p20_08.png','','Pimienta rosa, azafrán, pomelo','Tabaco, vainilla, cedro','Ámbar claro, incienso, pachulí, cashmeran'),
('Al Noble Safeer','LATTAFA',2800,10,'Unisex','/perfumes/p20_09.png','','Pomelo, bergamota, jengibre, pimienta negra','Caramelo, jazmín, heliotropo','Madera de guayaco, almizcle, cypriol, ámbar gris, cashmeran'),
('Al Noble Wazeer','LATTAFA',2800,10,'Unisex','/perfumes/p20_10.png','','Coñac, azafrán, nuez moscada, manzana','Cedro, sándalo, whisky, roble','Mirra, ambroxan, vainilla, almizcle'),
('Al Noble Ameer Mayar','LATTAFA',2800,10,'Unisex','/perfumes/p20_11.png','','Pimienta rosa, manzana, romero','Clavo, notas florales','Oud, pachulí, labdano, vetiver, ciprés'),
('Mayar Natural Intense','LATTAFA',3000,10,'Mujer','/perfumes/p20_12.png','','Lichi, frambuesa, hoja de violeta','Rosa blanca, peonía, jazmín','Almizcle, vainilla'),
('Mayar','LATTAFA',3000,10,'Mujer','/perfumes/p21_01.png','','Lichi, frambuesa, hoja de violeta','Rosa blanca, peonía, jazmín','Almizcle, vainilla'),
('Mayar Cherry Intense','LATTAFA',3400,10,'Mujer','/perfumes/p21_02.png','','','',''),
('Her Confession','LATTAFA',3800,10,'Mujer','/perfumes/p21_03.png','','','',''),
('His Confession','LATTAFA',3800,10,'Hombre','/perfumes/p21_04.png','','Canela, lavanda, mandarina','Iris, benjuí, ciprés, mahonial','Vainilla, haba tonka, ámbar, incienso, cedro, pachulí'),
('Eclaire','LATTAFA',2700,10,'Unisex','/perfumes/p21_05.png','','Caramelo, leche, azúcar','Miel, flores blancas','Vainilla, praliné, almizcle'),
('Banoffi','LATTAFA',5200,10,'Unisex','/perfumes/p21_06.png','','Crema de banana, dulce de leche','Crema batida, vainilla','Praliné, galleta, almizcle'),
('Pistache','LATTAFA',5200,10,'Unisex','/perfumes/p21_07.png','','Crema de pistacho, pistacho','Cacao, crema batida, coco','Vainilla, leche, almizcle'),
('Khamrah','LATTAFA',2500,10,'Unisex','/perfumes/p21_08.png','','Bergamota, canela, salvia sclarea','Praliné, tuberosa, frutas dulces','Vainilla, oud, mirra, haba tonka, benjuí, ámbar'),
('Khamrah Qahwa','LATTAFA',2700,10,'Unisex','/perfumes/p21_09.png','','Canela, cardamomo, jengibre','Praliné, frutas confitadas, flores blancas','Vainilla, café, haba tonka, benjuí, almizcle'),
('Sakeena','LATTAFA',3300,10,'Mujer','/perfumes/p21_10.png','','Maracuyá, notas ozónicas, mandarina','Frambuesa, rosa, flor de azahar, sal marina','Toffee, praliné, vainilla, almizcle'),
('Haya','LATTAFA',2700,10,'Mujer','/perfumes/p21_11.png','','Champán, fresa, mandarina, naranja sanguina, rosa','Gardenia, jazmín, orquídea de vainilla','Ámbar, sándalo, castaña'),
('Emaan','LATTAFA',3000,10,'Mujer','/perfumes/p21_12.png','','Flor de azahar, grosella negra, bergamota','Nardo, jazmín, caléndula','Almizcle, vainilla, cedro, pachulí'),
('Tharwah Gold','LATTAFA',3800,10,'Unisex','/perfumes/p22_01.png','','Azafrán, frambuesa','Rosa, oud','Vainilla, ámbar, almizcle'),
('Tharwah Silver','LATTAFA',3300,10,'Unisex','/perfumes/p22_02.png','','Menta, bergamota','Salvia sclarea, lavanda','Vetiver, almizcle, cedro'),
('Teriaq','LATTAFA',3600,10,'Unisex','/perfumes/p22_03.png','','Caramelo, almendra amarga, albaricoque, pimienta rosa','Miel, ruibarbo, flores blancas, rosa','Cuero, vainilla, almizcle, labdano, vetiver'),
('Teriaq Intense','LATTAFA',4000,10,'Unisex','/perfumes/p22_04.png','','Azafrán, bergamota','Licor de ciruela, canela','Ámbar, haba tonka, benjuí'),
('Musaman','LATTAFA',3650,10,'Unisex','/perfumes/p22_05.png','','Azafrán, mandarina italiana, lavanda','Amberwood, cedro de Virginia, geranio','Akigalawood, incienso, labdano'),
('Musaman White Intense Musaman','LATTAFA',3650,10,'Hombre','/perfumes/p22_06.png','','','',''),
('Musaman Black Intense','LATTAFA',4650,10,'Hombre','/perfumes/p22_07.png','','Lavanda, nuez moscada, salvia, bergamota','Cedro, geranio, rosyfolia, mahonial','Cocoapulse, haba tonka, arce, ambrofix, pachulí'),
('Al Qiam Gold','LATTAFA pride',3500,10,'Unisex','/perfumes/p22_08.png','','Azafrán, frambuesa','Cuero, pachulí','Oud, ámbar, benjuí, madera de guayaco, vetiver'),
('Al Qiam Silver','LATTAFA pride',3500,10,'Unisex','/perfumes/p22_09.png','','Bergamota, lavanda','Geranio, oud','Ámbar, almizcle, pachulí'),
('Ishq Shuukh Silver','LATTAFA pride',3400,10,'Unisex','/perfumes/p22_10.png','','Limón, bergamota','Piña, pimienta negra','Vainilla, amberwood, cedro, pachulí'),
('Ishq Shuukh Gold','LATTAFA pride',3400,10,'Unisex','/perfumes/p22_11.png','','Caramelo, azafrán','Ante, cuero, haba tonka','Vainilla, ámbar, almizcle'),
('Al Areeq Gold','LATTAFA pride',2900,10,'Unisex','/perfumes/p22_12.png','','Azafrán, té negro','Ante, cuero, incienso','Vainilla, amberwood, almizcle'),
('Bade''e Al Oud for Glory','LATTAFA',2600,10,'Unisex','/perfumes/p23_01.png','','Azafrán, nuez moscada, lavanda','Oud, pachulí','Oud, pachulí, almizcle'),
('Glory Bade''e Al Oud Amethyst','LATTAFA',2600,10,'Unisex','/perfumes/p23_02.png','','Pimienta rosa, bergamota','Rosa turca, rosa búlgara, jazmín','Oud, ámbar, vainilla'),
('Al Areeq Silver Bade''e','LATTAFA pride',2950,10,'Unisex','/perfumes/p23_03.png','','Cardamomo, manzana, lavanda','Tabaco, oud, ciprés, jazmín','Cuero, almizcle, sándalo, vainilla'),
('Bade''e Al Oud Sublime Bade''e','LATTAFA',2600,10,'Unisex','/perfumes/p23_04.png','','Manzana, lichi, rosa','Ciruela, jazmín','Musgo, vainilla, pachulí'),
('Bade''e A lOud Honor&Glory','LATTAFA',2800,10,'Unisex','/perfumes/p23_05.png','','Piña, crème brûlée','Canela, cúrcuma, pimienta negra, benjuí','Vainilla, sándalo, cashmeran, musgo'),
('Bade''e Al Oud Noble Blush','LATTAFA',2900,10,'Unisex','/perfumes/p23_06.png','','','',''),
('Dynasty','LATTAFA',2900,10,'Unisex','/perfumes/p23_07.png','','Bergamota, jengibre, salvia sclarea, frambuesa, nuez moscada','Té rooibos, ante','Cedro, cashmeran, amberwood'),
('AfeeF','LATTAFA',3500,10,'Unisex','/perfumes/p23_08.png','','Durazno, pimienta rosa, bergamota','Tuberosa, flor de azahar, jazmín','Praliné, sándalo, ámbar, pachulí'),
('Yara','LATTAFA',2400,10,'Mujer','/perfumes/p23_09.png','','Orquídea, heliotropo, mandarina','Acorde gourmand, frutas tropicales','Vainilla, almizcle, sándalo'),
('Yara Candy','LATTAFA',2500,10,'Mujer','/perfumes/p23_10.png','','','',''),
('Yara Elixir','LATTAFA',4600,10,'Mujer','/perfumes/p23_11.png','','','',''),
('Yara Moi','LATTAFA',3500,10,'Mujer','/perfumes/p23_12.png','','','',''),
('Yara Tous','LATTAFA',2500,10,'Mujer','/perfumes/p24_01.png','','','',''),
('Nebras','LATTAFA',3400,10,'Unisex','/perfumes/p24_02.png','','Frutos rojos, mandarina','Vainilla, cacao, rosa','Azúcar, haba tonka, ámbar, almizcle'),
('Nebras Elixir','LATTAFA',4500,10,'Unisex','/perfumes/p24_03.png','','Caramelo de leche, crema batida','Caña de azúcar, heliotropo','Vainilla, ambroxan, almizcle'),
('Angham','LATTAFA',3600,10,'Unisex','/perfumes/p24_04.png','','Jengibre, mandarina, pimienta rosa','Lavanda, praliné, cacao, jazmín','Vainilla, ámbar, almizcle'),
('The Kingdom Men The','LATTAFA',2800,10,'Hombre','/perfumes/p24_05.png','','','',''),
('The Kingdom Woman','LATTAFA',2800,10,'Mujer','/perfumes/p24_06.png','','Pera, peonía, cassis','Praliné, haba tonka, jazmín','Vainilla, almizcle, sándalo, ámbar'),
('Sehr','LATTAFA',4400,10,'Unisex','/perfumes/p24_07.png','','Almendra amarga, canela','Akigalawood, pomarosa, jazmín','Vainilla absoluta, haba tonka, ámbar'),
('Eternal Oud','LATTAFA',2800,10,'Unisex','/perfumes/p24_08.png','','Ciruela, pomelo','Heliotropo, orquídea','Ámbar, benjuí, vainilla, labdano, haba tonka, oud'),
('Petra','LATTAFA',4400,10,'Unisex','/perfumes/p24_09.png','','Ron, ciruela','Nardo, coco','Vainilla, almizcle, praliné'),
('Shaneen Silver','LATTAFA',3500,10,'Unisex','/perfumes/p24_10.png','','','',''),
('Shaneen Gold','LATTAFA',3500,10,'Unisex','/perfumes/p24_11.png','','Piña, pomelo','Higo, lavanda','Vainilla, pachulí, haba tonka'),
('Atlas','LATTAFA',3400,10,'Unisex','/perfumes/p24_12.png','','Notas marinas, sal, limón','Davana, iris','Ámbar gris, musgo de roble, sándalo'),
('Maahir Legacy','LATTAFA',2800,10,'Hombre','/perfumes/p25_01.png','','Lima, menta, pomelo, lavanda, piña','Pimienta negra, romero, enebro, geranio, incienso','Ambroxan, vetiver, musgo de roble, haba tonka, cashmeran'),
('Maahir Black Edition','LATTAFA',2800,10,'Hombre','/perfumes/p25_02.png','','Pimienta negra, pimienta rosa, azafrán','Aceite de cade, labdano, bálsamo de gurjan, ruibarbo','Cuero, cedro, madera de guayaco, pachulí, musgo, almizcle'),
('Maahir Gold Edition','LATTAFA',2800,10,'Hombre','/perfumes/p25_03.png','','','',''),
('Pisa','LATTAFA',3850,10,'Hombre','/perfumes/p25_04.png','','Mandarina, limón, bergamota','Cedro','Sándalo, ámbar'),
('Ajwad','LATTAFA',2800,10,'Unisex','/perfumes/p25_05.png','','Notas frutales','Rosa, jazmín','Vainilla, almizcle, ámbar, cedro'),
('Suqraat','LATTAFA',2950,10,'Unisex','/perfumes/p25_06.png','','Bergamota, jengibre','Lavanda, hoja de violeta','Almizcle, sándalo, ámbar'),
('Oud Najdia','LATTAFA',2950,10,'Unisex','/perfumes/p25_07.png','','Cítricos, cedro','Canela, oud, cardamomo, lavanda, romero','Ámbar, almizcle, pachulí'),
('Atheeri','LATTAFA',4400,10,'Mujer','/perfumes/p25_08.png','','Flor de la pasión, gota de rocío','Orquídea, jazmín','Vainilla, amberwood'),
('Give Me Gourmand Choco Overdose','LATTAFA',3900,10,'Unisex','/perfumes/p25_09.png','','Fudge de chocolate','Cacao, cupcake','Vainilla, caramelo, benjuí'),
('Give Me Gourmand Vanilla Freak','LATTAFA',4500,10,'Unisex','/perfumes/p25_10.png','','Cupcake','Azúcar, glaseado, almendra, canela','Mantequilla, vainilla, almizcle'),
('Give Me Gourmand Give Whipped Pleasure','LATTAFA',3900,10,'Unisex','/perfumes/p25_11.png','','Caramelo, caramelo salado, palomitas','Leche, jazmín','Haba tonka, benjuí, almizcle'),
('Give Me Gourmand Berry On Top','LATTAFA',4500,10,'Unisex','/perfumes/p25_12.png','','Fresa, crema chantilly','Mermelada de fresa, azúcar, flores blancas','Vainilla, almizcle'),
('Give Me Gourmand Mallow Madnes','LATTAFA',3900,10,'Unisex','/perfumes/p26_01.png','','Fresa, frambuesa','Malvavisco, fresia','Crema batida, vainilla, almizcle'),
('Give Me Gourmand Cookie Crave','LATTAFA',3900,10,'Unisex','/perfumes/p26_02.png','','Cacao, mantequilla','Galleta, leche, azúcar','Vainilla, crema batida, sándalo'),
('Art Of Universe','LATTAFA pride',3800,10,'Unisex','/perfumes/p26_03.png','','Mandarina, jengibre, bergamota, menta','Pera, flor de azahar','Almizcle, ámbar, cedro'),
('Art Of Arabia I','LATTAFA pride',3800,10,'Unisex','/perfumes/p26_04.png','','Bergamota, menta','Té negro, jengibre, lavanda','Ambroxan, incienso, canela'),
('Art Of Arabia II','LATTAFA pride',3900,10,'Unisex','/perfumes/p26_05.png','','Heliotropo, bergamota, cardamomo, pimienta rosa','Almendra, jazmín, lavanda','Oud, vainilla, madera de guayaco, sándalo'),
('Art ofArabia III','LATTAFA pride',3900,10,'Unisex','/perfumes/p26_06.png','','Olíbano, davana, bergamota','Dátiles, tabaco, sándalo, tuberosa','Mirra, vainilla, haba tonka, labdano, pachulí'),
('Art of Nature I','LATTAFA pride',3300,10,'Unisex','/perfumes/p26_07.png','','Higo, ciruela, grosella negra','Cuero, ruibarbo, rosa','Oud, ámbar gris, vainilla'),
('Art Of Nature II','LATTAFA pride',3100,10,'Unisex','/perfumes/p26_08.png','','Olíbano, mandarina, bergamota, manzana','Cardamomo, flor de azahar, rosa','Vainilla, almizcle, madera de guayaco, ambroxan, cedro'),
('Brioche Vanille Pride','LATTAFA pride',3600,10,'Unisex','/perfumes/p26_09.png','','Brioche, bergamota, fresia','Abeto balsámico, heliotropo','Vainilla, benjuí, praliné'),
('La Collection D Antiquites 1910','LATTAFA pride',3600,10,'Unisex','/perfumes/p26_10.png','','Manzana, davana, rosa','Cedro, osmanto','Vainilla, haba tonka, pachulí'),
('Artistan Ethnique','LATTAFA pride',2700,10,'Unisex','/perfumes/p26_11.png','','Ron, canela, azúcar','Caramelo, cacao, café, musgo de roble','Vainilla, haba tonka, madera de cachemira, labdano'),
('La Collection D Antiquites 1886','LATTAFA pride',3800,10,'Unisex','/perfumes/p26_12.png','','Bergamota, mate','Iris, haba tonka, jazmín, canela','Chocolate blanco, vainilla, tabaco blanco, almizcle, pachulí'),
('Vintage Radio','LATTAFA pride',2900,10,'Unisex','/perfumes/p27_01.png','','Lavanda, salvia, bergamota','Ciruela, palo santo, pimienta negra','Sándalo, oud'),
('Peace & Love','LATTAFA pride',3700,10,'Unisex','/perfumes/p27_02.png','','Almendra, grosella negra, bergamota','Rosa, tuberosa','Sándalo, vainilla, heliotropo'),
('Ladies Habik','LATTAFA',3600,10,'Mujer','/perfumes/p27_03.png','','Pera, bergamota','Muguete, jazmín, fresia','Almizcle, ámbar, musgo de roble'),
('Men''s Habik','LATTAFA',3400,10,'Hombre','/perfumes/p27_04.png','','','',''),
('Ameer Al Oud Intense Oud','LATTAFA',2900,10,'Hombre','/perfumes/p27_05.png','','Notas amaderadas, oud','Rosa, azafrán','Ámbar, almizcle, pachulí'),
('French Riviera','MANCERA',6800,10,'Unisex','/perfumes/p27_06.png','','Limón, naranja, mandarina, jengibre, pimienta','Notas marinas, flor de tiaré, pino, mimosa, vetiver','Sal marina, almizcle blanco, ámbar'),
('Instant Crush','MANCERA',6400,10,'Unisex','/perfumes/p27_07.png','','Azafrán, jengibre, mandarina y bergamota sicilianas','Amberwood, rosa marroquí, jazmín egipcio, pachulí','Vainilla de Madagascar, almizcle blanco, sándalo, musgo de roble'),
('Toy Boy','MOSCHINO',4600,10,'Hombre','/perfumes/p27_08.png','','Pimienta rosa, negra y blanca, pomelo','Rosa, cilantro, magnolia, nuez moscada','Cedro, sándalo, pachulí, ládano, almizcle'),
('Explorer Platinum','MONTBLANC',4300,10,'Hombre','/perfumes/p27_09.png','','Hoja de violeta','Salvia sclarea','Cedro'),
('Toy 2 Bubble Gum','MOSCHINO',4600,10,'Mujer','/perfumes/p27_10.png','','Cítricos confitados, limón y naranja italianos','Acorde de chicle, canela, arándanos, jengibre, rosa búlgara, durazno','Cedro, ambrofix, almizcle'),
('Ladies Toy 2','MOSCHINO',4600,10,'Mujer','/perfumes/p27_11.png','','Manzana, mandarina, bergamota, hoja de grosella','Peonía, magnolia, jazmín','Almizcle, sándalo, ámbar, notas amaderadas'),
('Toy 2 Pear','MOSCHINO',4600,10,'Mujer','/perfumes/p27_12.png','','Bergamota, manzana','Flor de azahar, jazmín','Almizcle, notas amaderadas'),
('Explorer','MONTBLANC',4300,10,'Hombre','/perfumes/p28_01.png','','Bergamota OrPur, salvia francesa, pimienta rosa','Vetiver OrPur, notas de piel','Pachulí, cacao, Ambrofix, Akigalawood'),
('Emblem','MONTBLANC',3800,10,'Hombre','/perfumes/p28_02.png','','Bergamota, cardamomo, artemisa','Canela, pimienta, salvia','Haba tonka, cuero, notas amaderadas'),
('Legend','MONTBLANC',4300,10,'Hombre','/perfumes/p28_03.png','','Hoja de lavanda, bergamota, piña, verbena, manzana','Rosa, geranio, manzana, frutos secos, musgo de roble, cumarina','Sándalo, haba tonka, almizcle'),
('Lengend Spirit','MONTBLANC',4300,10,'Hombre','/perfumes/p28_04.png','','Pomelo, bergamota, mandarina','Pimienta rosa, lavanda, notas acuáticas','Vetiver, madera de cachemira, musgo de roble'),
('Legend Night','MONTBLANC',4500,10,'Hombre','/perfumes/p28_05.png','','Cardamomo, salvia, lavanda','Angélica, ciprés, pimienta rosa','Ámbar, vainilla, madera de agar'),
('Night For Her','NARCISO RODRIGUEZ',3500,10,'Mujer','/perfumes/p28_06.png','Disponible en 2 presentaciones: RD$3,500 / RD$4,200','Flor de naranja africana, osmanto, bergamota','Almizcle, ámbar','Vetiver, pachulí, vainilla'),
('Her For Her Forever','RODRIGUEZ NARCISO RODRIGUEZ',3900,10,'Mujer','/perfumes/p28_07.png','Disponible en 2 presentaciones: RD$3,900 / RD$4,600','Rosa, bergamota','Almizcle, pachulí','Ámbar, vainilla, sándalo'),
('For Him Bleu Noir','NARCISO RODRIGUEZ',4400,10,'Hombre','/perfumes/p28_08.png','Disponible en 2 presentaciones: RD$4,400 / RD$5,600','Cardamomo, nuez moscada','Almizcle','Vetiver, cedro, madera de ébano, ámbar'),
('1 Million','PACO RABANNE',5600,10,'Hombre','/perfumes/p28_09.png','','Pomelo, naranja roja, menta','Rosa, canela, especias','Cuero, madera blanca, pachulí, ámbar'),
('1 Million Lucky','PACO RABANNE',8800,10,'Hombre','/perfumes/p28_10.png','','Ciruela, avellana','Miel, flor de osmanto','Ámbar, cedro, pachulí, haba tonka'),
('Phantom','PACO RABANNE',5700,10,'Hombre','/perfumes/p28_11.png','','Limón, lavanda','Manzana, notas verdes','Vainilla, pachulí, notas amaderadas'),
('Ladies Fame','PACO RABANNE',4300,10,'Mujer','/perfumes/p28_12.png','','Mango, bergamota','Jazmín, olíbano','Vainilla, sándalo'),
('Lady Million Prive','PACO RABANNE',6000,10,'Mujer','/perfumes/p29_01.png','','Frambuesa, neroli','Miel, gardenia, jazmín','Pachulí, ámbar, vainilla'),
('Lady Million','PACO RABANNE',5600,10,'Mujer','/perfumes/p29_02.png','','Frambuesa, neroli, limón de Amalfi','Jazmín, flor de naranja africana, gardenia','Miel blanca, pachulí, ámbar'),
('Lady Million','PACO RABANNE',5950,10,'Mujer','/perfumes/p29_03.png','','Frambuesa, neroli, limón de Amalfi','Jazmín, flor de naranja africana, gardenia','Miel blanca, pachulí, ámbar'),
('Lady Million','PACO RABANNE',5950,10,'Mujer','/perfumes/p29_04.png','','Frambuesa, neroli, limón de Amalfi','Jazmín, flor de naranja africana, gardenia','Miel blanca, pachulí, ámbar'),
('Phantom Intense','PACO RABANNE',5600,10,'Hombre','/perfumes/p29_05.png','','Limón, cardamomo','Lavanda, ládano','Vainilla, pachulí, incienso'),
('Olimpea','PACO RABANNE',5950,10,'Mujer','/perfumes/p29_06.png','','Jazmín acuático, mandarina verde, flor de jengibre','Vainilla, sal','Madera de cachemira, ámbar gris, sándalo'),
('Invictus','PACO RABANNE',5700,10,'Hombre','/perfumes/p29_07.png','','Pomelo, notas marinas, mandarina','Hoja de laurel, jazmín','Ámbar gris, madera de guayaco, roble, pachulí'),
('Invictus Victory','PACO RABANNE',5700,10,'Hombre','/perfumes/p29_08.png','','Pimienta rosa, limón','Olíbano, lavanda','Vainilla, ambroxan, notas amaderadas'),
('Invictus Victory Absolu','PACO RABANNE',10500,10,'Hombre','/perfumes/p29_09.png','','Pimienta, cardamomo','Incienso, ládano','Vainilla, pachulí, ámbar'),
('Invictus Victory','PACO RABANNE',6500,10,'Hombre','/perfumes/p29_10.png','','Pimienta rosa, limón','Olíbano, lavanda','Vainilla, ambroxan, notas amaderadas'),
('Invictus Parfum','PACO RABANNE',6500,10,'Hombre','/perfumes/p29_11.png','','Bergamota, pomelo','Ámbar gris, hoja de laurel','Vainilla, madera de guayaco, sal'),
('Invictus Victory ElixirI','PACO RABANNE',6900,10,'Hombre','/perfumes/p29_12.png','','Lavanda, cardamomo, pimienta negra','Incienso, pachulí','Vaina de vainilla, haba tonka'),
('Luna Rossa','PRADA',6300,10,'Hombre','/perfumes/p30_01.png','','Lavanda, bergamota, naranja amarga','Salvia, menta, pimienta','Ambroxan, notas amaderadas'),
('Ocean','PRADA',7000,10,'Hombre','/perfumes/p30_02.png','','Pomelo','Notas amaderadas, olíbano','Vainilla, Amber Xtreme'),
('Candy','PRADA',8400,10,'Mujer','/perfumes/p30_03.png','','Caramelo','Benjuí, almizcle','Vainilla, notas dulces'),
('Candy Florale','PRADA',6750,10,'Mujer','/perfumes/p30_04.png','','Bergamota, peonía','Caramelo, jazmín','Almizcle, vainilla, madera de guayaco'),
('Virtual Flower','PRADA',7500,10,'Unisex','/perfumes/p30_05.png','','','',''),
('Paradoxe Intense','PRADA',8550,10,'Mujer','/perfumes/p30_06.png','','Neroli, bergamota','Jazmín','Vainilla, ámbar, almizcle'),
('Pistachio Khair','PARIS CORNER PARIS',2800,10,'Unisex','/perfumes/p30_07.png','','Pistacho, helado, bergamota, avellana, cardamomo, ron','Pera, jazmín, peonía, geranio, frambuesa, durazno blanco','Crema batida, malvavisco, algodón de azúcar, haba tonka, cedro'),
('Confection Khair','PARIS CORNER',2800,10,'Mujer','/perfumes/p30_08.png','','Pera, crema batida','Cashmeran, jazmín, ylang ylang','Vainilla, malvavisco, sándalo'),
('Marshmallow Blush','PARIS CORNER',4350,10,'Unisex','/perfumes/p30_09.png','','Fresa, frambuesa, limón','Ambroxan, flor de azahar','Malvavisco, almizcle'),
('Hawas','RASASI',2700,10,'Hombre','/perfumes/p30_10.png','','Notas acuáticas, bergamota, canela, manzana, ciruela','Flor de azahar, pachulí','Ámbar gris, sándalo'),
('Hawas Black','RASASI',3700,10,'Hombre','/perfumes/p30_11.png','','Bergamota, piña, pomelo','Pachulí, notas amaderadas','Ámbar, musgo de roble'),
('Hawas Fire','RASASI',3800,10,'Hombre','/perfumes/p30_12.png','','Cítricos, pimienta, azafrán','Notas especiadas y aromáticas','Ámbar, notas amaderadas'),
('Hawas Ice','RASASI',3700,10,'Hombre','/perfumes/p31_01.png','','Manzana, limón italiano, bergamota siciliana, anís estrellado','Ciruela, flor de azahar, cardamomo','Almizcle, ámbar, madera de deriva, musgo'),
('Hawas Elixir','RASASI',3650,10,'Hombre','/perfumes/p31_02.png','','Menta, bergamota','Chocolate, especias','Vainilla, ámbar, almizcle'),
('Hawas For Her Eclat','RASASI',3900,10,'Mujer','/perfumes/p31_03.png','','','',''),
('Hawas For Her','RASASI',3500,10,'Mujer','/perfumes/p31_04.png','','','',''),
('Hawas Malibu','RASASI',4000,10,'Hombre','/perfumes/p31_05.png','','Piña, naranja, pomelo','Ámbar, iris, lavanda','Haba tonka, almizcle, pachulí, cashmeran'),
('Hawas Verde','RASASI',4000,10,'Hombre','/perfumes/p31_06.png','','Lima, romero, manzana verde','Pachulí','Ámbar'),
('Hawas Atlantis Hawas','RASASI',4900,10,'Hombre','/perfumes/p31_07.png','','Bergamota, limón, manzana, canela','Notas acuáticas, ciruela, cardamomo, flor de azahar','Madera de deriva, ámbar gris, pachulí, almizcle'),
('Hawas For Her Diva','RASASI',4000,10,'Mujer','/perfumes/p31_08.png','','','',''),
('Hawas Viper','RASASI',4000,10,'Hombre','/perfumes/p31_09.png','','Azafrán, cannabis, tomillo, notas verdes, davana','Tabaco, café, canela, violeta, frambuesa','Bálsamo de gurjan, almizcle, haba tonka'),
('Hawas Tropical','RASASI',4000,10,'Hombre','/perfumes/p31_10.png','','Agua de coco, hoja de higuera, jengibre','Coco, higo, menta','Sándalo, haba tonka, almizcle'),
('Hawas Kobra','RASASI',4000,10,'Hombre','/perfumes/p31_11.png','','Jengibre, bergamota, mandarina','Té verde, canela, neroli','Almizcle, notas amaderadas, ámbar'),
('Hawas for her Pink','RASASI',4300,10,'Mujer','/perfumes/p31_12.png','','','',''),
('Hawas London Uomo','RASASI',4900,10,'Hombre','/perfumes/p32_01.png','','Azafrán, pimienta rosa, pera','Rosa, olíbano, flores blancas','Maderas claras, ámbar, almizcle, vainilla'),
('Uomo Born In Roma','VALENTINO',8500,10,'Hombre','/perfumes/p32_02.png','','Jengibre, hoja de violeta, bergamota','Salvia, vetiver, notas minerales','Madera de cachemira, cuero'),
('Donna Born In Roma Coral Fantasy','VALENTINO',8500,10,'Mujer','/perfumes/p32_03.png','','','',''),
('Donna Born In Roma','VALENTINO',8700,10,'Mujer','/perfumes/p32_04.png','','Grosella negra, bergamota','Jazmín sambac','Vainilla bourbon, notas amaderadas'),
('Uomo Born In Roma Intense','VALENTINO',8500,10,'Hombre','/perfumes/p32_05.png','','Cardamomo, salvia, jengibre','Ambrox, olíbano','Vainilla, haba tonka, cuero'),
('Coral Fantasy','Uomo Born In Roma',7500,10,'Hombre','/perfumes/p32_06.png','','Mandarina, jengibre','Hoja de violeta, geranio','Vetiver, cashmeran'),
('Donna Born In Roma Intense','VALENTINO',8000,10,'Mujer','/perfumes/p32_07.png','','Bergamota','Jazmín','Vainilla, ámbar, sándalo'),
('Eros','VERSACE',5000,10,'Hombre','/perfumes/p32_08.png','','Menta, manzana verde, limón','Haba tonka, ambroxan, geranio','Vainilla de Madagascar, cedro, vetiver, musgo de roble'),
('Eros Flame','VERSACE',5500,10,'Hombre','/perfumes/p32_09.png','','','',''),
('Eros Najim','VERSACE',7500,10,'Hombre','/perfumes/p32_10.png','','','',''),
('Yellow Diamond','VERSACE',5000,10,'Mujer','/perfumes/p32_11.png','','','',''),
('Bright Crystal','VERSACE',6700,10,'Mujer','/perfumes/p32_12.png','','Yuzu, granada, notas heladas','Peonía, loto, magnolia','Almizcle, caoba, ámbar'),
('Dylan Blue','VERSACE',4900,10,'Hombre','/perfumes/p33_01.png','','Bergamota de Calabria, pomelo, hoja de higuera, notas acuáticas','Hoja de violeta, madera de papiro, pachulí, pimienta negra, ambrox','Almizcle mineral, haba tonka, incienso, azafrán'),
('Dylan Purple','VERSACE',6300,10,'Mujer','/perfumes/p33_02.png','','Naranja amarga, bergamota, pera','Fresia púrpura','Pomarosa, mahonial, iso-e-super, ambroxan'),
('Dylan Tourquoise','VERSACE',4600,10,'Mujer','/perfumes/p33_03.png','','Limón, mandarina, pimienta rosa','Guayaba, fresia, cassis, jazmín','Almizcle, clearwood, cedro'),
('Dylan Blue','VERSACE',4700,10,'Hombre','/perfumes/p33_04.png','','Bergamota de Calabria, pomelo, hoja de higuera, notas acuáticas','Hoja de violeta, madera de papiro, pachulí, pimienta negra, ambrox','Almizcle mineral, haba tonka, incienso, azafrán'),
('SpiceBomb Extreme','VICTOR & ROLD',6000,10,'Hombre','/perfumes/p33_05.png','','','',''),
('SpiceBomb Dark Leather','VICTOR & ROLF',6000,10,'Hombre','/perfumes/p33_06.png','','','',''),
('Spicebomb Metallic Musk','ROLF VICTOR & ROLF',9100,10,'Hombre','/perfumes/p33_07.png','','','',''),
('FlowerBomb','VICTOR & ROLF',6500,10,'Mujer','/perfumes/p33_08.png','','','',''),
('Libre','YVES SAINT LAURENT',7600,10,'Mujer','/perfumes/p33_09.png','','Lavanda, mandarina, grosella negra, petitgrain','Lavanda, flor de azahar, jazmín','Vainilla de Madagascar, almizcle, cedro, ámbar gris'),
('Libre / Le Parfum','YVES SAINT LAURENT',8000,10,'Mujer','/perfumes/p33_10.png','','Mandarina, azafrán, jengibre','Lavanda, flor de azahar, jazmín','Vainilla, miel, ámbar gris, haba tonka'),
('Ysl','YVES SAINT LAURENT',7600,10,'Hombre','/perfumes/p33_11.png','','Bergamota, jengibre, salvia','Salvia sclarea, geranio, manzana','Ámbar gris, incienso, cedro, haba tonka'),
('Ysl EDP','YVES SAINT LAURENT',8000,10,'Hombre','/perfumes/p33_12.png','','Bergamota, jengibre, salvia','Salvia sclarea, geranio, manzana','Ámbar gris, incienso, cedro, haba tonka'),
('Ladies Black Opium Glitter','YVES SAINT LAURENT',8700,10,'Mujer','/perfumes/p34_01.png','','Pera, pimienta rosa, flor de azahar','Café, jazmín, almendra amarga, regaliz','Vainilla, pachulí, madera de cachemira, cedro'),
('Glitter Black Opium','YVES SAINT LAURENT',6900,10,'Mujer','/perfumes/p34_02.png','','Pera, pimienta rosa, flor de azahar','Café, jazmín, almendra amarga, regaliz','Vainilla, pachulí, madera de cachemira, cedro'),
('Tiramisu Caramel','ZIMAYA',2900,10,'Unisex','/perfumes/p34_03.png','','Caramelo','Miel, cumarina, notas amaderadas','Vainilla, whisky, almizcle'),
('Tiramisu Coco','ZIMAYA',3300,10,'Unisex','/perfumes/p34_04.png','','Amaretto, café','Helado, vainilla, galleta','Vainilla, azúcar moreno, ámbar'),
('Tiramisu S mores','ZIMAYA',3100,10,'Unisex','/perfumes/p34_05.png','','Chocolate, malvavisco, café, bergamota, flor de nectarina','Bizcocho, vainilla, leche, almizcle, almendra','Azúcar, caramelo, notas cremosas, almizcle, ámbar'),
('Mazaaj Rhythm','ZIMAYA',3100,10,'Unisex','/perfumes/p34_06.png','','Pomelo, bergamota','Jengibre, manzana verde','Almizcle, ámbar'),
('Mazaaj Infused','ZIMAYA',3100,10,'Hombre','/perfumes/p34_07.png','','Bergamota, azafrán','Rosa, oud','Ámbar, almizcle, pachulí');